#Conectar a Drive y leer documento

---

In [1]:
# Conectar Colab con drive.
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

In [ ]:
# Importa libreria.
import pandas as pd

In [1]:
# Establecer conexion al documento
path = "/content/drive/MyDrive/Colab Notebooks/DB/retail_sales_dataset.csv"
df = pd.read_csv(path)

NameError: name 'pd' is not defined

#Muestra las primeras 10 filas del DataFrame
Esto sirve para confirmar que los datos se han cargado correctamente.

In [ ]:
top_10 = df.head(10)
print(f"10 primeras filas:\n\n{top_10}")

10 primeras filas:

   Transaction ID        Date Customer ID  Gender  Age Product Category  \
0               1  2023-11-24     CUST001    Male   34           Beauty
1               2  2023-02-27     CUST002  Female   26         Clothing
2               3  2023-01-13     CUST003    Male   50      Electronics
3               4  2023-05-21     CUST004    Male   37         Clothing
4               5  2023-05-06     CUST005    Male   30           Beauty
5               6  2023-04-25     CUST006  Female   45           Beauty
6               7  2023-03-13     CUST007    Male   46         Clothing
7               8  2023-02-22     CUST008    Male   30      Electronics
8               9  2023-12-13     CUST009    Male   63      Electronics
9              10  2023-10-07     CUST010  Female   52         Clothing

   Quantity  Price per Unit  Total Amount
0         3              50           150
1         2             500          1000
2         1              30            30
3         1             500           500
4         2              50           100
5         1              30            30
6         2              25            50
7         4              25           100
8         2             300           600
9         4              50           200

#Exploraci√≥n Inicial de los Datos

In [ ]:
# Muestra las √∫ltimas 5 filas del DataFrame.
ultimas_5 = df.tail(5)
print(f"5 ultimas filas:\n\n{ultimas_5}")

5 ultimas filas:

     Transaction ID        Date Customer ID  Gender  Age Product Category  \
995             996  2023-05-16     CUST996    Male   62         Clothing
996             997  2023-11-17     CUST997    Male   52           Beauty
997             998  2023-10-29     CUST998  Female   23           Beauty
998             999  2023-12-05     CUST999  Female   36      Electronics
999            1000  2023-04-12    CUST1000    Male   47      Electronics

     Quantity  Price per Unit  Total Amount
995         1              50            50
996         3              30            90
997         4              25           100
998         3              50           150
999         4              30           120

In [ ]:
# Utiliza el m√©todo info() para obtener informaci√≥n general sobre el DataFrame,
# incluyendo el n√∫mero de entradas, nombres de las columnas, tipos de datos y memoria utilizada.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   object
 2   Customer ID       1000 non-null   object
 3   Gender            1000 non-null   object
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   object
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), object(4)
memory usage: 70.4+ KB

In [ ]:
# Genera estad√≠sticas descriptivas del DataFrame utilizando el m√©todo describe().
descriptivas = df.describe()
print(f"Estadisticas Descriptivas:\n\n{descriptivas}")

Estadisticas Descriptivas:

       Transaction ID         Age     Quantity  Price per Unit  Total Amount
count     1000.000000  1000.00000  1000.000000     1000.000000   1000.000000
mean       500.500000    41.39200     2.514000      179.890000    456.000000
std        288.819436    13.68143     1.132734      189.681356    559.997632
min          1.000000    18.00000     1.000000       25.000000     25.000000
25%        250.750000    29.00000     1.000000       30.000000     60.000000
50%        500.500000    42.00000     3.000000       50.000000    135.000000
75%        750.250000    53.00000     4.000000      300.000000    900.000000
max       1000.000000    64.00000     4.000000      500.000000   2000.000000

#Inspecci√≥n de los Datos

In [ ]:
# Inspecciona los tipos de datos de cada columna utilizando el atributo dtypes.
print(f"Tipos de datos:\n\n{df.dtypes}")

Tipos de datos:

Transaction ID       int64
Date                object
Customer ID         object
Gender              object
Age                  int64
Product Category    object
Quantity             int64
Price per Unit       int64
Total Amount         int64
dtype: object

In [ ]:
# Cuenta los valores √∫nicos en la columna Producto utilizando el m√©todo value_counts().
cnt_valores_unicos_product = df["Product Category"].value_counts()
print(f"Conteo de valores unicos en Producto:\n\n{cnt_valores_unicos_product}")

Conteo de valores unicos en Producto:

Product Category
Clothing       351
Electronics    342
Beauty         307
Name: count, dtype: int64

In [ ]:
# Muestra todos los valores √∫nicos en la columna Customer ID utilizando el m√©todo unique().
cnt_valores_unicos_Customer_id = df["Customer ID"].unique()
print(f"Valores unicos en Customer ID:\n\n{cnt_valores_unicos_Customer_id}")

Valores unicos en Customer ID:

['CUST001' 'CUST002' 'CUST003' 'CUST004' 'CUST005' 'CUST006' 'CUST007'
 'CUST008' 'CUST009' 'CUST010' 'CUST011' 'CUST012' 'CUST013' 'CUST014'
 'CUST015' 'CUST016' 'CUST017' 'CUST018' 'CUST019' 'CUST020' 'CUST021'
 'CUST022' 'CUST023' 'CUST024' 'CUST025' 'CUST026' 'CUST027' 'CUST028'
 'CUST029' 'CUST030' 'CUST031' 'CUST032' 'CUST033' 'CUST034' 'CUST035'
 'CUST036' 'CUST037' 'CUST038' 'CUST039' 'CUST040' 'CUST041' 'CUST042'
 'CUST043' 'CUST044' 'CUST045' 'CUST046' 'CUST047' 'CUST048' 'CUST049'
 'CUST050' 'CUST051' 'CUST052' 'CUST053' 'CUST054' 'CUST055' 'CUST056'
 'CUST057' 'CUST058' 'CUST059' 'CUST060' 'CUST061' 'CUST062' 'CUST063'
 'CUST064' 'CUST065' 'CUST066' 'CUST067' 'CUST068' 'CUST069' 'CUST070'
 'CUST071' 'CUST072' 'CUST073' 'CUST074' 'CUST075' 'CUST076' 'CUST077'
 'CUST078' 'CUST079' 'CUST080' 'CUST081' 'CUST082' 'CUST083' 'CUST084'
 'CUST085' 'CUST086' 'CUST087' 'CUST088' 'CUST089' 'CUST090' 'CUST091'
 'CUST092' 'CUST093' 'CUST094' 'CUST095' 'CUST096' 'CUST097' 'CUST098'
 'CUST099' 'CUST100' 'CUST101' 'CUST102' 'CUST103' 'CUST104' 'CUST105'
 'CUST106' 'CUST107' 'CUST108' 'CUST109' 'CUST110' 'CUST111' 'CUST112'
 'CUST113' 'CUST114' 'CUST115' 'CUST116' 'CUST117' 'CUST118' 'CUST119'
 'CUST120' 'CUST121' 'CUST122' 'CUST123' 'CUST124' 'CUST125' 'CUST126'
 'CUST127' 'CUST128' 'CUST129' 'CUST130' 'CUST131' 'CUST132' 'CUST133'
 'CUST134' 'CUST135' 'CUST136' 'CUST137' 'CUST138' 'CUST139' 'CUST140'
 'CUST141' 'CUST142' 'CUST143' 'CUST144' 'CUST145' 'CUST146' 'CUST147'
 'CUST148' 'CUST149' 'CUST150' 'CUST151' 'CUST152' 'CUST153' 'CUST154'
 'CUST155' 'CUST156' 'CUST157' 'CUST158' 'CUST159' 'CUST160' 'CUST161'
 'CUST162' 'CUST163' 'CUST164' 'CUST165' 'CUST166' 'CUST167' 'CUST168'
 'CUST169' 'CUST170' 'CUST171' 'CUST172' 'CUST173' 'CUST174' 'CUST175'
 'CUST176' 'CUST177' 'CUST178' 'CUST179' 'CUST180' 'CUST181' 'CUST182'
 'CUST183' 'CUST184' 'CUST185' 'CUST186' 'CUST187' 'CUST188' 'CUST189'
 'CUST190' 'CUST191' 'CUST192' 'CUST193' 'CUST194' 'CUST195' 'CUST196'
 'CUST197' 'CUST198' 'CUST199' 'CUST200' 'CUST201' 'CUST202' 'CUST203'
 'CUST204' 'CUST205' 'CUST206' 'CUST207' 'CUST208' 'CUST209' 'CUST210'
 'CUST211' 'CUST212' 'CUST213' 'CUST214' 'CUST215' 'CUST216' 'CUST217'
 'CUST218' 'CUST219' 'CUST220' 'CUST221' 'CUST222' 'CUST223' 'CUST224'
 'CUST225' 'CUST226' 'CUST227' 'CUST228' 'CUST229' 'CUST230' 'CUST231'
 'CUST232' 'CUST233' 'CUST234' 'CUST235' 'CUST236' 'CUST237' 'CUST238'
 'CUST239' 'CUST240' 'CUST241' 'CUST242' 'CUST243' 'CUST244' 'CUST245'
 'CUST246' 'CUST247' 'CUST248' 'CUST249' 'CUST250' 'CUST251' 'CUST252'
 'CUST253' 'CUST254' 'CUST255' 'CUST256' 'CUST257' 'CUST258' 'CUST259'
 'CUST260' 'CUST261' 'CUST262' 'CUST263' 'CUST264' 'CUST265' 'CUST266'
 'CUST267' 'CUST268' 'CUST269' 'CUST270' 'CUST271' 'CUST272' 'CUST273'
 'CUST274' 'CUST275' 'CUST276' 'CUST277' 'CUST278' 'CUST279' 'CUST280'
 'CUST281' 'CUST282' 'CUST283' 'CUST284' 'CUST285' 'CUST286' 'CUST287'
 'CUST288' 'CUST289' 'CUST290' 'CUST291' 'CUST292' 'CUST293' 'CUST294'
 'CUST295' 'CUST296' 'CUST297' 'CUST298' 'CUST299' 'CUST300' 'CUST301'
 'CUST302' 'CUST303' 'CUST304' 'CUST305' 'CUST306' 'CUST307' 'CUST308'
 'CUST309' 'CUST310' 'CUST311' 'CUST312' 'CUST313' 'CUST314' 'CUST315'
 'CUST316' 'CUST317' 'CUST318' 'CUST319' 'CUST320' 'CUST321' 'CUST322'
 'CUST323' 'CUST324' 'CUST325' 'CUST326' 'CUST327' 'CUST328' 'CUST329'
 'CUST330' 'CUST331' 'CUST332' 'CUST333' 'CUST334' 'CUST335' 'CUST336'
 'CUST337' 'CUST338' 'CUST339' 'CUST340' 'CUST341' 'CUST342' 'CUST343'
 'CUST344' 'CUST345' 'CUST346' 'CUST347' 'CUST348' 'CUST349' 'CUST350'
 'CUST351' 'CUST352' 'CUST353' 'CUST354' 'CUST355' 'CUST356' 'CUST357'
 'CUST358' 'CUST359' 'CUST360' 'CUST361' 'CUST362' 'CUST363' 'CUST364'
 'CUST365' 'CUST366' 'CUST367' 'CUST368' 'CUST369' 'CUST370' 'CUST371'
 'CUST372' 'CUST373' 'CUST374' 'CUST375' 'CUST376' 'CUST377' 'CUST378'
 'CUST379' 'CUST380' 'CUST381' 'CUST382' 'CUST383' 'CUST384' 'CUST385'
 'CUST386' 'CUST387' 'CUST388' 'CUST389' 'CUST390' 'CUST391' 'CUST392'
 'CUST393' 'CUST394' 'CUST395' 'CUST396' 'CUST397' 'CUST398' 'CUST399'
 'CUST400' 'CUST401' 'CUST402' 'CUST403' 'CUST404' 'CUST405' 'CUST406'
 'CUST407' 'CUST408' 'CUST409' 'CUST410' 'CUST411' 'CUST412' 'CUST413'
 'CUST414' 'CUST415' 'CUST416' 'CUST417' 'CUST418' 'CUST419' 'CUST420'
 'CUST421' 'CUST422' 'CUST423' 'CUST424' 'CUST425' 'CUST426' 'CUST427'
 'CUST428' 'CUST429' 'CUST430' 'CUST431' 'CUST432' 'CUST433' 'CUST434'
 'CUST435' 'CUST436' 'CUST437' 'CUST438' 'CUST439' 'CUST440' 'CUST441'
 'CUST442' 'CUST443' 'CUST444' 'CUST445' 'CUST446' 'CUST447' 'CUST448'
 'CUST449' 'CUST450' 'CUST451' 'CUST452' 'CUST453' 'CUST454' 'CUST455'
 'CUST456' 'CUST457' 'CUST458' 'CUST459' 'CUST460' 'CUST461' 'CUST462'
 'CUST463' 'CUST464' 'CUST465' 'CUST466' 'CUST467' 'CUST468' 'CUST469'
 'CUST470' 'CUST471' 'CUST472' 'CUST473' 'CUST474' 'CUST475' 'CUST476'
 'CUST477' 'CUST478' 'CUST479' 'CUST480' 'CUST481' 'CUST482' 'CUST483'
 'CUST484' 'CUST485' 'CUST486' 'CUST487' 'CUST488' 'CUST489' 'CUST490'
 'CUST491' 'CUST492' 'CUST493' 'CUST494' 'CUST495' 'CUST496' 'CUST497'
 'CUST498' 'CUST499' 'CUST500' 'CUST501' 'CUST502' 'CUST503' 'CUST504'
 'CUST505' 'CUST506' 'CUST507' 'CUST508' 'CUST509' 'CUST510' 'CUST511'
 'CUST512' 'CUST513' 'CUST514' 'CUST515' 'CUST516' 'CUST517' 'CUST518'
 'CUST519' 'CUST520' 'CUST521' 'CUST522' 'CUST523' 'CUST524' 'CUST525'
 'CUST526' 'CUST527' 'CUST528' 'CUST529' 'CUST530' 'CUST531' 'CUST532'
 'CUST533' 'CUST534' 'CUST535' 'CUST536' 'CUST537' 'CUST538' 'CUST539'
 'CUST540' 'CUST541' 'CUST542' 'CUST543' 'CUST544' 'CUST545' 'CUST546'
 'CUST547' 'CUST548' 'CUST549' 'CUST550' 'CUST551' 'CUST552' 'CUST553'
 'CUST554' 'CUST555' 'CUST556' 'CUST557' 'CUST558' 'CUST559' 'CUST560'
 'CUST561' 'CUST562' 'CUST563' 'CUST564' 'CUST565' 'CUST566' 'CUST567'
 'CUST568' 'CUST569' 'CUST570' 'CUST571' 'CUST572' 'CUST573' 'CUST574'
 'CUST575' 'CUST576' 'CUST577' 'CUST578' 'CUST579' 'CUST580' 'CUST581'
 'CUST582' 'CUST583' 'CUST584' 'CUST585' 'CUST586' 'CUST587' 'CUST588'
 'CUST589' 'CUST590' 'CUST591' 'CUST592' 'CUST593' 'CUST594' 'CUST595'
 'CUST596' 'CUST597' 'CUST598' 'CUST599' 'CUST600' 'CUST601' 'CUST602'
 'CUST603' 'CUST604' 'CUST605' 'CUST606' 'CUST607' 'CUST608' 'CUST609'
 'CUST610' 'CUST611' 'CUST612' 'CUST613' 'CUST614' 'CUST615' 'CUST616'
 'CUST617' 'CUST618' 'CUST619' 'CUST620' 'CUST621' 'CUST622' 'CUST623'
 'CUST624' 'CUST625' 'CUST626' 'CUST627' 'CUST628' 'CUST629' 'CUST630'
 'CUST631' 'CUST632' 'CUST633' 'CUST634' 'CUST635' 'CUST636' 'CUST637'
 'CUST638' 'CUST639' 'CUST640' 'CUST641' 'CUST642' 'CUST643' 'CUST644'
 'CUST645' 'CUST646' 'CUST647' 'CUST648' 'CUST649' 'CUST650' 'CUST651'
 'CUST652' 'CUST653' 'CUST654' 'CUST655' 'CUST656' 'CUST657' 'CUST658'
 'CUST659' 'CUST660' 'CUST661' 'CUST662' 'CUST663' 'CUST664' 'CUST665'
 'CUST666' 'CUST667' 'CUST668' 'CUST669' 'CUST670' 'CUST671' 'CUST672'
 'CUST673' 'CUST674' 'CUST675' 'CUST676' 'CUST677' 'CUST678' 'CUST679'
 'CUST680' 'CUST681' 'CUST682' 'CUST683' 'CUST684' 'CUST685' 'CUST686'
 'CUST687' 'CUST688' 'CUST689' 'CUST690' 'CUST691' 'CUST692' 'CUST693'
 'CUST694' 'CUST695' 'CUST696' 'CUST697' 'CUST698' 'CUST699' 'CUST700'
 'CUST701' 'CUST702' 'CUST703' 'CUST704' 'CUST705' 'CUST706' 'CUST707'
 'CUST708' 'CUST709' 'CUST710' 'CUST711' 'CUST712' 'CUST713' 'CUST714'
 'CUST715' 'CUST716' 'CUST717' 'CUST718' 'CUST719' 'CUST720' 'CUST721'
 'CUST722' 'CUST723' 'CUST724' 'CUST725' 'CUST726' 'CUST727' 'CUST728'
 'CUST729' 'CUST730' 'CUST731' 'CUST732' 'CUST733' 'CUST734' 'CUST735'
 'CUST736' 'CUST737' 'CUST738' 'CUST739' 'CUST740' 'CUST741' 'CUST742'
 'CUST743' 'CUST744' 'CUST745' 'CUST746' 'CUST747' 'CUST748' 'CUST749'
 'CUST750' 'CUST751' 'CUST752' 'CUST753' 'CUST754' 'CUST755' 'CUST756'
 'CUST757' 'CUST758' 'CUST759' 'CUST760' 'CUST761' 'CUST762' 'CUST763'
 'CUST764' 'CUST765' 'CUST766' 'CUST767' 'CUST768' 'CUST769' 'CUST770'
 'CUST771' 'CUST772' 'CUST773' 'CUST774' 'CUST775' 'CUST776' 'CUST777'
 'CUST778' 'CUST779' 'CUST780' 'CUST781' 'CUST782' 'CUST783' 'CUST784'
 'CUST785' 'CUST786' 'CUST787' 'CUST788' 'CUST789' 'CUST790' 'CUST791'
 'CUST792' 'CUST793' 'CUST794' 'CUST795' 'CUST796' 'CUST797' 'CUST798'
 'CUST799' 'CUST800' 'CUST801' 'CUST802' 'CUST803' 'CUST804' 'CUST805'
 'CUST806' 'CUST807' 'CUST808' 'CUST809' 'CUST810' 'CUST811' 'CUST812'
 'CUST813' 'CUST814' 'CUST815' 'CUST816' 'CUST817' 'CUST818' 'CUST819'
 'CUST820' 'CUST821' 'CUST822' 'CUST823' 'CUST824' 'CUST825' 'CUST826'
 'CUST827' 'CUST828' 'CUST829' 'CUST830' 'CUST831' 'CUST832' 'CUST833'
 'CUST834' 'CUST835' 'CUST836' 'CUST837' 'CUST838' 'CUST839' 'CUST840'
 'CUST841' 'CUST842' 'CUST843' 'CUST844' 'CUST845' 'CUST846' 'CUST847'
 'CUST848' 'CUST849' 'CUST850' 'CUST851' 'CUST852' 'CUST853' 'CUST854'
 'CUST855' 'CUST856' 'CUST857' 'CUST858' 'CUST859' 'CUST860' 'CUST861'
 'CUST862' 'CUST863' 'CUST864' 'CUST865' 'CUST866' 'CUST867' 'CUST868'
 'CUST869' 'CUST870' 'CUST871' 'CUST872' 'CUST873' 'CUST874' 'CUST875'
 'CUST876' 'CUST877' 'CUST878' 'CUST879' 'CUST880' 'CUST881' 'CUST882'
 'CUST883' 'CUST884' 'CUST885' 'CUST886' 'CUST887' 'CUST888' 'CUST889'
 'CUST890' 'CUST891' 'CUST892' 'CUST893' 'CUST894' 'CUST895' 'CUST896'
 'CUST897' 'CUST898' 'CUST899' 'CUST900' 'CUST901' 'CUST902' 'CUST903'
 'CUST904' 'CUST905' 'CUST906' 'CUST907' 'CUST908' 'CUST909' 'CUST910'
 'CUST911' 'CUST912' 'CUST913' 'CUST914' 'CUST915' 'CUST916' 'CUST917'
 'CUST918' 'CUST919' 'CUST920' 'CUST921' 'CUST922' 'CUST923' 'CUST924'
 'CUST925' 'CUST926' 'CUST927' 'CUST928' 'CUST929' 'CUST930' 'CUST931'
 'CUST932' 'CUST933' 'CUST934' 'CUST935' 'CUST936' 'CUST937' 'CUST938'
 'CUST939' 'CUST940' 'CUST941' 'CUST942' 'CUST943' 'CUST944' 'CUST945'
 'CUST946' 'CUST947' 'CUST948' 'CUST949' 'CUST950' 'CUST951' 'CUST952'
 'CUST953' 'CUST954' 'CUST955' 'CUST956' 'CUST957' 'CUST958' 'CUST959'
 'CUST960' 'CUST961' 'CUST962' 'CUST963' 'CUST964' 'CUST965' 'CUST966'
 'CUST967' 'CUST968' 'CUST969' 'CUST970' 'CUST971' 'CUST972' 'CUST973'
 'CUST974' 'CUST975' 'CUST976' 'CUST977' 'CUST978' 'CUST979' 'CUST980'
 'CUST981' 'CUST982' 'CUST983' 'CUST984' 'CUST985' 'CUST986' 'CUST987'
 'CUST988' 'CUST989' 'CUST990' 'CUST991' 'CUST992' 'CUST993' 'CUST994'
 'CUST995' 'CUST996' 'CUST997' 'CUST998' 'CUST999' 'CUST1000']

#Filtrado de Datos

In [ ]:
# Filtra el DataFrame para mostrar solo las filas donde el Total de ventas Sea mayor a 50.
fltr_total_sales = (df["Total Amount"] > 50)
mayores_50 = df[fltr_total_sales]
print(f"Filas donde el Total Amount es mayor a 50:\n\n{mayores_50}")

Filas donde el Total Amount es mayor a 50:

     Transaction ID        Date Customer ID  Gender  Age Product Category  \
0                 1  2023-11-24     CUST001    Male   34           Beauty
1                 2  2023-02-27     CUST002  Female   26         Clothing
3                 4  2023-05-21     CUST004    Male   37         Clothing
4                 5  2023-05-06     CUST005    Male   30           Beauty
7                 8  2023-02-22     CUST008    Male   30      Electronics
..              ...         ...         ...     ...  ...              ...
993             994  2023-12-18     CUST994  Female   51           Beauty
996             997  2023-11-17     CUST997    Male   52           Beauty
997             998  2023-10-29     CUST998  Female   23           Beauty
998             999  2023-12-05     CUST999  Female   36      Electronics
999            1000  2023-04-12    CUST1000    Male   47      Electronics

     Quantity  Price per Unit  Total Amount
0           3              50           150
1           2             500          1000
3           1             500           500
4           2              50           100
7           4              25           100
..        ...             ...           ...
993         2             500          1000
996         3              30            90
997         4              25           100
998         3              50           150
999         4              30           120

[783 rows x 9 columns]

In [ ]:
# Filtra el DataFrame para mostrar solo las filas donde el precio (Precio) sea menor a 0.5.
fltr_price_sales = (df["Price per Unit"] < 0.5)
menores_ = df[fltr_price_sales]
print(f"Filas donde los precios son menor a 0.5:\n\n{menores_}")

Filas donde los precios son menor a 0.5:

Empty DataFrame
Columns: [Transaction ID, Date, Customer ID, Gender, Age, Product Category, Quantity, Price per Unit, Total Amount]
Index: []

In [ ]:
# Utilizando el m√©todo query(), filtra el DataFrame para mostrar las filas donde el producto sea Beauty y las ventas sean mayores a 30.
datos_filtrados = df.query("`Product Category` == 'Beauty' and `Total Amount` > 30")
print(f"Filas donde el Tipo de producto sea Beauty y el total de ventas sea mayor a 30:\n\n {datos_filtrados}")

Filas donde el Tipo de producto sea Beauty y el total de ventas sea mayor a 30:

      Transaction ID        Date Customer ID  Gender  Age Product Category  \
0                 1  2023-11-24     CUST001    Male   34           Beauty
4                 5  2023-05-06     CUST005    Male   30           Beauty
11               12  2023-10-30     CUST012    Male   35           Beauty
20               21  2023-01-14     CUST021  Female   50           Beauty
24               25  2023-12-26     CUST025  Female   64           Beauty
..              ...         ...         ...     ...  ...              ...
981             982  2023-12-19     CUST982  Female   46           Beauty
989             990  2023-05-25     CUST990  Female   58           Beauty
993             994  2023-12-18     CUST994  Female   51           Beauty
996             997  2023-11-17     CUST997    Male   52           Beauty
997             998  2023-10-29     CUST998  Female   23           Beauty

     Quantity  Price per Unit  Total Amount
0           3              50           150
4           2              50           100
11          3              25            75
20          1             500           500
24          1              50            50
..        ...             ...           ...
981         3              30            90
989         2             500          1000
993         2             500          1000
996         3              30            90
997         4              25           100

[273 rows x 9 columns]

#Slicing de Datos

In [ ]:
# Selecciona y muestra solo las columnas Producto y Ventas del DataFrame.
product_total = df[["Product Category","Total Amount"]]
print(f"Categorias y Total de venta:\n\n{product_total}")

Categorias y Total de venta:

    Product Category  Total Amount
0             Beauty           150
1           Clothing          1000
2        Electronics            30
3           Clothing           500
4             Beauty           100
..               ...           ...
995         Clothing            50
996           Beauty            90
997           Beauty           100
998      Electronics           150
999      Electronics           120

[1000 rows x 2 columns]

In [ ]:
# Utilizando loc[], selecciona y muestra las filas de la 5 a la 10 (inclusive) y las columnas Producto y Total Amount.
columnas_5_10 = df.loc[5:10, ["Product Category","Total Amount"]]
print(f"Filas desde 5 a 10 mostrando solo Categoria Producto y Total Amount:\n\n {columnas_5_10}")

Filas desde 5 a 10 mostrando solo Categoria Producto y Total Amount:

    Product Category  Total Amount
5            Beauty            30
6          Clothing            50
7       Electronics           100
8       Electronics           600
9          Clothing           200
10         Clothing           100

In [ ]:
# Utilizando iloc[], selecciona y muestra las primeras 5 filas y las primeras 3 columnas del DataFrame.
primeras_5f_3c = df.iloc[:5, :3]
print(f"Primeras 5 filas y primeras 3 columnas:\n\n{primeras_5f_3c}")

Primeras 5 filas y primeras 3 columnas:

   Transaction ID        Date Customer ID
0               1  2023-11-24     CUST001
1               2  2023-02-27     CUST002
2               3  2023-01-13     CUST003
3               4  2023-05-21     CUST004
4               5  2023-05-06     CUST005